### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sibbl** [ocombe/ocModal#18]
The project currently has no license, so it's protected and all rights are reserved ([source](https://help.github.com/articles/licensing-a-repository/)).

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Is this intentional or are you planning to add an open source license anytime in the future?

**Comment by ocombe** [comment]
Hello, the license is MIT as specified in package.json: https://github.com/ocombe/ocModal/blob/master/package.json#L6
